site_name: dream

# Details about the theme used in the website.
theme:
  name: material
  font:
    code: Consolas
  palette:
    # The dark theme.
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # The light theme.
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    annotation: material/plus-circle

  features:
    # This sets up the next/previous page links in the footer.
    - navigation.footer
    # This lets users copy code snippets.
    - content.code.copy

# This sets up the structure of the website.
nav:
  - Home: index.md
  - "B2: Symmetry and relativity":
      - PS1: b2_ps1.md
  - "B6: Condensed matter physics":
      - PS1: b6_ps1.md
      - PS2: b6_ps2.md

# Some necessary extensions.
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
